### ISSUE TITLE
thread 'main' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by srwalter** [alexcrichton/futures-rs#105]
I'm getting a bizarre error at runtime:

thread 'main' panicked at 'assertion failed: `(left == right)` (left: `140241379868944`, right: `140241379869200`)', /home/srwalter/.cargo/git/checkouts/futures-rs-a4f11d094efefb0a/master/src/lib.rs:208

If this is caused by an error in my program, I'm at a loss to understand what I'm doing wrong.  Attached is a test case that should reproduce the error.  At a high level I'm trying to adapt a socket into a Stream of messages.  From the backtrace it seems to be failing in read_exact() called by my poll() implementation, but I can't find anything that looks like the assertion printed.

[main2.txt](https://github.com/alexcrichton/futures-rs/files/438497/main2.txt)

Note that you'll need a listening socket at localhost:1234 for the program to connect to; I just used netcat: nc -l 127.0.0.1:1234

**Comment by alexcrichton** [comment]
Thanks for the report! This is a pretty poor panic message, and I should update that!

The problem here is that you're creating a `TaskData<T>` on one task and then accessing it on another. This is specifically done by `TaskIo`. You've got two calls to create tasks, one is `lazy(|| { ... }).forget()` and the other is `ChunkStream::new(). ... .forget()`. I think you can change this to `lazy(|| { ... ; ChunkStream::new(...) }).forget()` and it'll fix the problems. That is, spawn only one task instead of two.

Let me know if that doesn't work out though!

**Comment by srwalter** [comment]
That got it!  Thanks!
