### ISSUE TITLE
Coroutines as futures?

### ISSUE THREAD

**Issue by dpc** [alexcrichton/futures-rs#223]
I'm not sure if I should as here, on in tokio...

It seems to me it should be relatively easy to implement `Future` or `Stream` for a coroutine (like coroutine generator), where every poll, would resume a given coroutine, then the coroutine would do it's things, and suspend itself when it blocked.

After some googling I've found: https://github.com/cstorey/fringe-futures  (ping @cstorey), and I wonder if any other projects like that are ongoing.

Any thoughts?

**Comment by cstorey** [comment]
Hi,

My implementation is mostly a half baked proof of concept, as I found that
there were a few corners in the fringe API that made things difficult.

The other one that's worth looking at is https://github.com/erickt/stateful
.

Longer term, I'd expect that coroutine support would be left to third party
packages, though. You might have more luck asking on the Reddit for prior
art, too.

Cheers,

**Comment by dpc** [comment]
@cstorey Thanks for info! Could you expand on the corner cases?

**Comment by cstorey** [comment]
Mostly:
 * I can't see a way to get a final "return value" from a fringe Generator without either overloading the generator protocol, or passing in a boxed reference that gets written to.
 * There's no easy way to clean-up a stack, and any resources it owns, without passing a Sentinel  value into the generator to ask it to panic (although there's a PR for that functionality).

**Comment by alexcrichton** [comment]
Thanks for the report! I think the answer here sort of depends on what the coroutines are doing over time.

If you've got a generator, for example, where values are yielded over time then that definitely matches `Stream` moreso than `Future`. Blocking in the coroutine translates to `NotReady`, items translate to `Ready(Some(item))` and when the coroutine exits that translates to `Ready(None)`.

If you've just got a coroutine generating a value, however, then that's much more analagous to a `Future`. That is, throughout its lifetime it'll block, returning `NotReady`. At the end it'll return `Ready(t)` with the computed value.

Note that this does require that the sources of blocking are "futures powered" where they're connected to the current future task, otherwise the wakeups may not be delivered appropriately.

**Comment by dpc** [comment]
@cstorey I'm not planing to use `yielder` so it's going to be easy to distinguish between yielded values and final result. I talked with libfringe authors about coroutine stack unwinding and they are working on it. I'm worried, especially in the light of changing `panic` to `abort` to default that all coroutine libraries will be left without proper way to unwind. As long as there's way to force unwind, it should be OK.

**Comment by dpc** [comment]
Some prototyping: https://github.com/dpc/tokio-fiber . I'm keeping in touch with libfringe devs about other pain points.

**Comment by alexcrichton** [comment]
I think there's probably not a whole lot more to follow up with on this thread specifically, so I'm going to close, but I'll happily reopen if I'm mistaken!
