### ISSUE TITLE
Thoughts on implementing what is `FramedIo` now as `Sink

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#237]
I've been thinking some about how to port what is `FramedIo` today -> `Sink` (for the write half).

The main complication I see is that `poll_complete` is supposed to return `Ready` when it is done flushing essentially. It's basically used as a fn to "poke" the internal state machine to make progress.

The problem is that some `FramedIo` implementations would have no clear "complete" stage. Imagine a `FramedIo` that does some sort of keep alive ping. Every 30 seconds, the value sends a ping message to the other end to keep the state alive.

In this case, how is `poll_complete` implemented? What does it return? It seems to me that the combinators seem to assume that there is an "at rest" stage and it also seems to be that one only needs to call `poll_complete` until it returns `Ready`. If this is correct, then a value that implements ping on a timer can never return ready because it will be continuously setting timeouts and sending ping messages. If it never returns ready from poll_complete, then none of the combinator functions will work as expected...

On the other hand, if `poll_complete` ever does return `Ready`, then pings will simply not fire if the `Sink` is idle, which defeats the goal of the keep alive ping logic.

**Comment by alexcrichton** [comment]
Hm, definitely an interesting conundrum! I might expect this to be encoded via:

* Assume `poll_complete` is always called
* Register timers in `poll_complete`, wakeups of the current task will cause this fn to be called again
* The `poll_complete` returns `Ready` even though it's schedule to write a ping later (when `poll_complete` is called

I see the `Read` from `poll_complete` as "I'm ready to accept more messages". So long as you're not actively writing out a ping message that should presumably be the case for a ping middleware I believe.

I haven't though too much about the interactions of combinators and `poll_complete` returning `Ready` even though there's an event queued. Could you elaborate on your worries here?

**Comment by aturon** [comment]
We discussed this on IRC a bit. Some basic points:

- This likely affects streams as well, in that we cannot necessarily rely on a stream user to poll repeatedly in a timely fashion (they may not want elements from the stream, for a variety of reasons).

- The suggestion "The poll_complete returns Ready even though it's schedule to write a ping later" is problematic, since you still need to ensure that the sink user call `poll_complete` again when woken -- but a "clever" user may avoid it, since they already know that polling is complete.

- We can solve this basic problem by introducing a hidden task in the lower levels of the protocol, but that involves introducing channels to talk to the client task. This is fine for 0.1.

- Going forward, we may want to consider a general story for an object that needs to be "poked" on every task wakeup -- perhaps a notion of subtask. But we're punting for now.

**Comment by alexcrichton** [comment]
I believe we've since resolved this, so closing.

**Comment by carllerche** [comment]
This is not resolved, it has been punted to 0.2

**Comment by aturon** [comment]
Yes, we need to get this all sorted out still.

**Comment by aturon** [comment]
Closing; the current plan here is to handle this through the `Transport` trait at the proto level.
