### ISSUE TITLE
Recent commit to mpsc clone fn introduces potential state hazards

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#267]
I believe this commit should be reverted: https://github.com/alexcrichton/futures-rs/commit/dd3d102ebb9147f88542792a9ad4ae0b9aa4309b

The original implementation, while more complex, was intended to maintain correctness. The issues with the changes are two fold:

1) It enables overflow of max senders, which in turn could cause more senders than intended to exist.
2) It corrupts the state such that once senders are dropped, enabling the creation of additional senders, `clone` will still fail.

**Comment by alexcrichton** [comment]
> which in turn could cause more senders than intended to exist.

I'm not sure I understand how this can happen, can you elaborate?

> It corrupts the state such that once senders are dropped

I'm also not quite sure how this happens, can you elaborate?

**Comment by carllerche** [comment]
There is a race between the inc and the dec

Imagine you are at the max sender limit. 

Thread one clones, incs past max. 
Thread two drops sender 
Thread three clones, inc is still above max because thread 1 didn't dec. clone fails even though it should succeed. 

This is a real case if I am reading the patch correctly. You could also theoretically setup a similar case with many threads causing an overflow, though today that is unlikely to be possible without hitting system resource limits. That being said, it seems prudent to not leave flaws that are guarded by system resource limits in case future changes somehow make hitting the limit possible. Imagine sharing the sender atomic to store additional state. 

Either way, the max sender race is real and correctness trumps readability IMO.

**Comment by alexcrichton** [comment]
Hm so while this isn't quite the case right now, I think we can safely assume that `MAX_CAPACITY = usize::max() / 2`. This means that `MAX_BUFFER = usize::max() / 4`. This means that the maximum number of senders is either:

* `usize::max() / 2 - buffer`
* `usize::max() / 4`

For the latter case it's not something we need to worry about as all senders take up at least 4 bytes. For the former case you'd have to have a buffer on the order of `usize::max() / 2`. With that I'd conclude that because each sender takes up at least 2 bytes, we can't ever hit this case.

With that in mind, isn't it basically impossible ever to hit this? Like we don't need an assert at all really, it's just a somewhat sanity check like the case on `Arc::clone`.

In that sense if anything overflows we should *abort*, not panic, as the state of the channel is the least of our concerns at that point.

**Comment by carllerche** [comment]
While technically correct, a pathological case could be demonstrated by forgetting the senders. You would need to abort at the very least, however IMO since correctness is possible without too much more code, avoiding leaving landmines for future changes is preferred. Also, any newcomer to the code will read the shorter impl and see the flaw and have to backtrack the reasoning for why leaving the flaw is acceptable. Or there can be a comment with the full explanation which will probably be longer than the code being deleted.
