### ISSUE TITLE
Should `tokio_core::net::TcpStream::connect` also support `tokio_core::reactor::Remote`?

### ISSUE THREAD

**Issue by kkimdev** [alexcrichton/futures-rs#292]
Maybe it also makes sense to support `Remote` argument in addition to `Handle`?

**Comment by alexcrichton** [comment]
Thanks for the report! Although this may be more appropriate for the [tokio-core](https://github.com/tokio-rs/tokio-core) repository in the future.

Unfortunately though `TcpStream` can't support `Remote` in quite the same way because it wouldn't otherwise be able to return immediately with a registered TCP stream. The `Remote` type, though, offers the ability to spawn a future and you could use a `oneshot` to learn of the result from a remote spawn.
