### ISSUE TITLE
Adding a `fork()` function for Streams

### ISSUE THREAD

**Issue by Ameobea** [alexcrichton/futures-rs#370]
In an application I've been working on, I've encountered a need to implementing a sort of MPMC functionality for futures.  The application produces an `impl Stream` that needs to be handed off to multiple consumers dynamically.  This seems like it could be very useful to include in the library itself, and I wanted to know what you thought about it.

In order to implement this functionality, I've been creating a new `(tx, rx) = channel(0);` to map it into the parent stream.   This essentially produces a "fork" stream that yields the same values as shown by the very basic code below:

```rust
// the new fork stream
let (tx, rx) = channel(0);
// the parent stream
let strm: BoxStream<BrokerResult, ()> = self.push_stream_recv.take().unwrap();

// wrap the fork sender in an option so we can move out of it to `send()` without issues
let mut tx_opt = Some(tx);
let new_strm = strm.map(move |msg| {
    // unfortunate workaround needed since `send()` takes `self`
    let mut tx = tx_opt.take().unwrap();
    tx = tx.send(msg.clone()).wait().unwrap();
    tx_opt = Some(tx);
    msg
});
// 
self.push_stream_recv = Some(new_strm.boxed());
rx
```

This produces a graph that looks something like this:
![](https://ameo.link/u/3y7.png)

----

Some important things to take into consideration:
 - If a bounded sender is used such as that in the example code above, the messages received on the fork `rx` will need to be consumed in order to drive the whole tree forward.  I've encountered issues with this in my application where when the tail sender is replaced in the struct after returning a fork to a client, the entire flow halts due to the messages not being consumed there.
 - Errors can occur during the transmission of ticks to the fork if the `rx` half of the fork is dropped by a client.  This will probably require error checking within the `map()` closure to avoid breaking the whole tree due to this.
 - There may be a better way to do this (creating true MPMC data structures that handle this internally and more efficiently) or you may not want to include this kind of functionality in the main library.

In any case, I'd love to hear what you think about this.

**Comment by carllerche** [comment]
I'm working on a broadcast channel, which may be helpful: http://github.com/carllerche/futures-broadcast/

**Comment by Ameobea** [comment]
@carllerche looks really good so far!  I definitely think that some kind of MPMC should be added into this library one way or another; it has so many potential use cases.

**Comment by schets** [comment]
This would probably have to be a different type since not all streams can fork (what if the value isn't Clone or Sync?) but it's quite useful.  You can look at [MultiQueue](https://github.com/schets/multiqueue) for now, which can do this sort of broadcast.

> If a bounded sender is used such as that in the example code above, the messages received on the fork rx will need to be consumed in order to drive the whole tree forward. 

This can be really desirable behavior (except for the issues on drop and receiver churn, which any broadcast queue should handle). It keeps various parts of the system relatively in sync and keeps upstream producers from overwhelming only part of the system. Since it looks like you're using the queue for a trading system that last part is especially important if you ever put money into it, otherwise you'll just make nonsense trades.

Other than that, all of the error cases have to be handled by the queue itself for correctness so you shouldn't have to worry.

**Comment by alexcrichton** [comment]
Whoa awesome, thanks for the link @schets! That looks like quite a thorough library :)

**Comment by schets** [comment]
I'm not really sure if it makes sense to have a ForkableStream trait in futures, I don't see what it would add over allowing datastructures to simply broadcast to multiple Streams internally. Maybe there are use cases outside of broadcasting queue messages, or some waiting edge-case that I'm not aware of?

There might be an argument around allowing generics over ForkableStreams instead of just streams, but would that belong in futures?

**Comment by alexcrichton** [comment]
Oh yeah the complications here in the various implementations I've seen have convinced me that we probably want to let this functionality bake outside the `futures` crate itself before trying to bring it in tree.

**Comment by alexcrichton** [comment]
I'm going to close this in favor of the ongoing work (@carllerche's and @schets's libraries above) and it looks weighty enough that we likely won't move in this crate soon.
