### ISSUE TITLE
futures 0.1.11 breaks semver

### ISSUE THREAD

**Issue by TeXitoi** [alexcrichton/futures-rs#415]
futures-cpupool does not compile anymore because `complete` is now deprecated and behind a feature gate.

https://travis-ci.org/TeXitoi/benchmarksgame-rs/jobs/211146538

**Comment by ustulation** [comment]
Same for me. I think there have been API breaking changes throughout with the patch version history. I would normally expect `~x.y.z` to work forever if it worked once, but that is not the case for futures. Is this intended, because if so I'm planning on using `=x.y.z` (or if that leads to conflict with other updates of crates common to futures and my crate) maybe even submit a `.lock` file to crates.io.

It would be nice though if patch versiion changes didn't cause API breakage, but ya, would like to know if that's intended for this crate.

**Comment by carllerche** [comment]
Hmm, the issue is actually that futures-cpupool opts out of backwards compatibility. I'm not sure why. So, I would say this would be an issue w/ futures-cpupool

**Comment by alexcrichton** [comment]
Argh yes sorry this is my mistake, I should not have published a futures-cpupool that relies on disabling the "with-deprecated" feature, that's crucial for backcompat!

I'll fix pronto.

**Comment by alexcrichton** [comment]
Yes so FWIW 0.1.11 is a non-breaking change. It simply deprecates existing functionality.

That being said the futures crate *also* has the ability to expose breaking changes by disabling the `with-deprecated` feature (which is enabled by default). I've been using this to help updating the various crates throughout the Tokio ecosystem, but this has the problem of I may accidentally publish a crate that actually disables the feature (that's never intended to happen by default)

**Comment by ustulation** [comment]
Ah thanks, deprecation causes lint errors for us, so will probably will have to relax the lints a little in our crates. Btw would making any API related changes be a non-patch update be doable (including API deprecation) ? (Depending on that i'll have to change my Cargo.toml accordinly).

**Comment by alexcrichton** [comment]
Oh yeah sorry also to be clear in general a new lint warning is not considered a breaking change (even with `#![deny(warnings)]`). The rationale for this is that it only affects your crate, not your crate used as a dependency (where lints are always capped).

Could you clarify what you mean by API changes in a non-patch change? Do you mean altering the futures release process?

**Comment by TeXitoi** [comment]
Thanks, fixed here.

**Comment by ustulation** [comment]
@alexcrichton right. What i was saying was if my `Cargo.toml` had a dep at `dep = "~0.1.4"` i would normally expect to do cargo update and not expect any breakage because even if it goes to `"~0.1.20` after the update, all it means is that internal stuff changed (better logic/implementation etc.) while the API (external public stuff which affects me) was unchanged. If the API changed however and if it requires me to touch my code, i would expect that to be `0.2.x` in which case i would be consiously making an effort to interface with the new API.

Similary if my crate compiled for me and had a dependency `dep = "~0.1.4"` and that was uploaded to the repository, anyone doing a fresh build / cargo update could get `0.2.0 > dep >= 0.1.4` and would expect that to just build. It won't if say `0.1.5` had breaking API changes.

At-least that is what's in my head for these versiion thingies - might be wrong.

**Comment by alexcrichton** [comment]
Ah so the way that we're interpreting the "semver track of `0.1.*`" releases is that we'll basically do anything we need to that's backwards compatible. In that sense we'll never land a breaking change, but it doesn't mean that we won't land deprecations.

In general we're still in the early-ish stages of developing the futures library, so we just want to make sure we've got room to fix up mistakes we've learned from the past :)

If this is causing lots of problems though please let us know! It's our intention that the 0.1.* upgrades are a smooth experience, but if we're being too aggressive with deprecations we can back them out for a few versions to allow time to upgrade and then add them back in later.

**Comment by carllerche** [comment]
@ustulation what you'd described should be correct **as long** as you don't turn warnings into hard errors. Adding new warnings is not considered a breaking change.

**Comment by ustulation** [comment]
Ya, will probably relax the lints a little in some of our crates. Thanks guys !
