### ISSUE TITLE
Why can't the type be inferred inside `spawn_fn`

### ISSUE THREAD

**Issue by yaa110** [alexcrichton/futures-rs#447]
Please consider the following examples:

**Example 1**

```rust
let pool = CpuPool::new(2);
let local_packages = pool.spawn_fn(|| {
        let s = get_a_string();
        let res: Result<String, ()> = Ok(s);
        res
});
```

**Example 2**

```rust
let pool = CpuPool::new(2);
let local_packages = pool.spawn_fn(|| {
        let s = get_a_string();
        let res = Ok(s);
        res
});
```

The first example is compiled, however, the second one is not compiled with the error of `error[E0283]: type annotations required: cannot resolve _: std::marker::Send`, why should the type of `res` be provided?

*rustc --version*: rustc 1.16.0 (30cf806ef 2017-03-10)

**Comment by stuhood** [comment]
Because in the second case the error type of the Result is unknowable: the compiler can't infer from that example what the type of an Err for this Result would be. And afaik, rust does not have a "bottom" type (like scala's `Nothing`) which is legal to use in any position.

In practice though, the function context in which the Future is used will allow both types to be inferred.

**Comment by carllerche** [comment]
You can probably do something like:

```rust
Ok::<_, ()>(get_a_string())
```

Basically only specifying the error type
