### ISSUE TITLE
Inconsistent naming of associated types for `Future`, `Stream` and `Sink`

### ISSUE THREAD

**Issue by photino** [alexcrichton/futures-rs#535]
For the traits [`Future`](https://docs.rs/futures/0.1.14/futures/future/trait.Future.html) and [`Stream`](https://docs.rs/futures/0.1.14/futures/stream/trait.Stream.html), the associated types are `Item` and `Error`.  However, for the [`Sink` ](https://docs.rs/futures/0.1.14/futures/sink/trait.Sink.html) trait, the associated types are `SinkItem` and `SinkError`. The naming of associated types are not consistent.

**Comment by alexcrichton** [comment]
Thanks for the report! This is actually intentional, however, because it's common to implement both `Sink` and `Stream` traits for a type. By having one use `Item` and one use `SinkItem` (sinks are a little less common) you don't have to use unusual syntax to disambiguate and instead projections like `Foo::Item` work as expected.
