### ISSUE TITLE
Consume Stream by more than one Sink?

### ISSUE THREAD

**Issue by daschl** [alexcrichton/futures-rs#603]
Hi,

I haven't found this in the API docs I assume its not possible right now but I wanted to raise/ask it here: is it possible to consume a stream somehow from two sinks? I understand that there might be more overhead involved with borrowing but my use case is I have a data pipeline which currently has one sink (like a database). But I also want to allow lets say my stdout sink to print what the database sink is writing out. (right now my code can select either or).

The related question is how to split a Stream into N "downstream streams" that I can consume individually?

**Comment by carllerche** [comment]
If you are dealing with multiple sinks, you have to decide if:

a) You will dispatch to the sinks in lock step. In which case, you are limited by the slowest sink.
b) You add a buffering layer so that sinks can operate at different rates.

Implementing a) would be a fairly straight forward combinator. Implementing b) is a lot more tricky. I was experimenting w/ [futures-broadcast](github.com/carllerche/futures-broadcast) a while ago, which would basically support that case, but it is far from ready.

**Comment by daschl** [comment]
@carllerche thanks yeah I think a buffering would make most sense in terms of scalability. Note that I need that maybe more or less anyways if I want to support the case where the underlying sink is currently not ready to consume and I have data incoming without stalling it immediately (or handling bursts in a more graceful manner)

Would the same approach apply to consuming streams from more than one consumer?

**Comment by carllerche** [comment]
I think so.

**Comment by carllerche** [comment]
It looks like the issue is resolved and has gone inactive. I'll close it now.
