### ISSUE TITLE
Second thoughts on the `blocking` construct

### ISSUE THREAD

**Issue by aturon** [alexcrichton/futures-rs#656]
Sorry for second-guessing this after approving the PR, but I'm having some second thoughts about having both `blocking` *and* `CurrentThread`:

- The two provide very similar, but not identical functionality. The RFC, however, specifies an API for `CurrentThread` that makes it much more similar to `blocking` on a future.
- `blocking` does not allow you to spawn tasks onto the current thread, but it's unclear why that's a benefit. OTOH, having both means that when you want to go async->sync, you need to determine whether you're calling anything that expects to be run within `CurrentThread` (so that it can spawn).

I know part of the rationale was dealing with streams and sinks, but if we put that aside for a second and focus on futures, can we try to spell out in more detail why it makes sense to have this split?

cc @carllerche

**Comment by carllerche** [comment]
While similar, `CurrentThread` and `blocking` handle two different use cases.

`blocking` handles the bride from async -> sync when outside of an execution context (the async system lives on other threads).

`CurrentThread` sets up an execution context that is geared towards running futures on the current thread.

Specifically, `CurrentThread` adds significant pepper to handle the case that `blocking` supports. i.e., blocking the current thread and unblocking as soon as the supplied future is resolved:

```rust
CurrentThread::block_with_init(
    my_future.then(|res| {
        CurrentThread::cancel_all_running();
        res
    })
```

Compared with:

```rust
blocking(fut).wait();
```

This added pepper is intentional as `CurrentThread` is designed to support multiplexing execution of unrelated futures on the current thread. I would even say that, making it common to call `cancel_all_running` is not really something that we should do as it can result in unexpected behavior (multiplexed tasks being dropped).

**Comment by aturon** [comment]
First, let me say I grok the two use-cases and agree that their needs *may* be distinct. But, OTOH, part of my point is that the use-cases blur together, somewhat. In particular, if you're trying to use a library that expects to be run within a current thread executor, you'll have to set things up differently than just calling `blocking`.

That said, I think maybe what you're getting at is that you believe this forced split is a *good* thing, because it requires the caller to acknowledge that there are additional tasks beyond the one provided by the initial future, and that has implications for blocking. Or, put differently, it requires acknowledging that a full-fledged *executor* is required.

Thanks for laying this out. I think this is a good move. Closing.

**Comment by carllerche** [comment]
@aturon 

> That said, I think maybe what you're getting at is that you believe this forced split is a good thing, because it requires the caller to acknowledge that there are additional tasks beyond the one provided by the initial future, and that has implications for blocking. Or, put differently, it requires acknowledging that a full-fledged executor is required.

Yes, that is exactly it.
