### ISSUE TITLE
Make methods -> impl Future

### ISSUE THREAD

**Issue by bestouff** [alexcrichton/futures-rs#657]
Make `.map()` and its friends look like:
```rust
fn map<U>(self, f: impl FnOnce(Self::Item) -> U) -> impl Future<U>;
```
- This will have to wait for at least [RFC 1951](https://rust-lang.github.io/rfcs/1951-expand-impl-trait.html).
- It will break backwards compatibility, but hey isn't that precisely what a 0.1 version is for ?
- On the bright side: it will simplify `Future`'s ergonomics a lot.

(See discussion: https://users.rust-lang.org/t/will-impl-future-replace-return-types-of-combinators-like-map-and-and-then/13969/5)

**Comment by carllerche** [comment]
What is the value of switching to `impl Future`? Many of these combinators provide additional fns.

**Comment by carllerche** [comment]
What is the value of switching to `impl Future`? Many of these combinators provide additional fns, such as get_ref, get_mut, into_inner, etc...

**Comment by stbuehler** [comment]
And as far as I can tell it would prevent you from putting values of those return types into structs, unless you either make it generic (for no good reason) or box it.

**Comment by alexcrichton** [comment]
Thanks for the report! But unfortunately yeah I don't think that we'll be able to do this. At the lowest layer (the `futures` crate) we often want to add extra functionality to these combinators such as acquiring references to the interior, moving ownership back out, etc. These operations are above and beyond the `Future` trait itself so we need to use concrete types instead of `impl Future`. That being said though I'd love to explore ways to improve the documentation here! I think that may be a bit of a rustdoc bug then rather than this-crate-bug :(
