### ISSUE TITLE
futures::future::Executor is not practically useful

### ISSUE THREAD

**Issue by BusyJay** [alexcrichton/futures-rs#673]
Considering following case:

```
fn handle_task_async<TypeOfF, E: Executor<TypeOfF>>(e: &E) {
    let f = gen_f();
    e.execute(f)
}
```

To make above example work, I have to type the exact type of `f` in function `handle_task_async`'s signature. However, the type of `f` can be too complicated to be figured out. So a box is necessary.

It would be better if the signature of `execute` becomes `fn execute<F: Future>(f: F)`. That way the compiler can handling the types by itself.

**Comment by alexcrichton** [comment]
Thanks for the report! One of the primary motivations, though, for having the type parameter on the trait was to allow implementations to place restrictions on what kind of futures they can execute. For example some are sendable, some are non-sendable, etc. If the type parameter is on the method then that isn't possible.

That being said the `Executor` trait as-is also isn't necessarily intended to be super widely used. It's mostly meant for some low-level abstractions, if necessary, but otherwise isn't intended to be super broadly used.

**Comment by alexcrichton** [comment]
I'm going to close this for now since this is working as expected, but we can always consider more targeted feature requests as well!
