### ISSUE TITLE
Stream: Pipe, back pressure

### ISSUE THREAD

**Issue by killercup** [alexcrichton/futures-rs#69]
Be warned: I didn't do much research before writing this and was just wondering if the abstractions provided here allow implementing some of the nice features of node's streams. Commencing brain dump…

---

I saw that the only place where back pressure in streams is addressed is the documentation for `futures::stream::channel`, which says

> This channel is unique in that it implements back pressure to ensure that the sender never outpaces the receiver. The Sender::send method will only allow sending one message and the next message can only be sent once the first was consumed.

This sounds like its very specific to that one implementation. Is there a plan to generalize this? I/O streams using internal buffers would also need some kind of 'high water mark' (node.js calls it that way IIRC) or a way to pause streams they depend on when their buffer is full.

---

This brings me to my next question: Is there a plan to introduce a `pipe` method? I.e., a method that works like pipe in a shell by combining multiple stream processors? `and_then` allows transforming each item of a stream, but `pipe` would go a bit further than that, using the current stream's output as input for the next stream.

For example: A stream of data read from an HTTP request (the body of the request) is piped into a (streaming) JSON parser whose output is piped into CSV serialization which then writes to a file. Ideally, this would 'just' be `http::get("https://some.example/data").pipe(Json::array_deserializer::<SomeStruct>()).pipe(Csv::from).pipe(File::writeStream(filename))`. I guess there is _a lot_ of work involved to make something like this work (and a lot more crates, and implicit worker/event loop handling somehow).

A `Pipeable` trait might become pretty complicated if you wanted it to handle back pressure across `n` piped streams. If I'm not mistaken, it could abstract over `map` and `and_then` as well (implementing it for closures that return `Self::Item` or `Future<Item, Error>` resp.).

**Comment by carllerche** [comment]
Back pressure handling is built into the entire stream system (and future system) in a much more robust way than node has done IMO. Your future / stream construction represents the flow of data from the leaves (where data enters the future/stream system) down to the root future... the one you use to trigger the computation.

Since future-rs works via poll instead of push (and this is what is unique about futures-rs), none of the combinators will buffer up data. Instead, they will only operate when the entire system has capacity to handle more data. This means that buffering logic is delegated to the leaf futures aka the ones that push data into the system from the outside world (I should note that you can also add explicit buffering points by using a buffer combinator).

The reason why `futures::stream::channel` has the note that you pointed out is because it is a "leaf node" in your future computation. Aka, you use it to push data in.

Another point of comparison vs. node's streams. Since future-rs is entirely poll based, there is no need for a function to "pause" the stream. You simply don't poll. This is important because "pausing" a concurrent computation is inherently racy. A `poll` strategy has clearer guarantees.

**Comment by alexcrichton** [comment]
Indeed! I think @carllerche covered it pretty well, in that the theory is "backpressure" is everywhere by default.

We may eventually want to add some sort of `Sender::pipe` method on the sending half of a channel which pipes one stream into a channel, but that should also handle backpressure by default due to the polling effects.

As I think this is basically all taken care of, closing, but thanks for the report!
