### ISSUE TITLE
Consider Adding `takeOne` to `Stream`

### ISSUE THREAD

**Issue by andreytkachenko** [alexcrichton/futures-rs#703]
Stream::takeOne returns future for next item from stream (it behaves just like `into_future`, but does not consumes the stream, same as `take`)

It will be much easier to process a stream in item-by-item manner.

**Comment by carllerche** [comment]
Sorry, I'm not following. `into_future` consumes `self` as well. Maybe you could provide the fn signature you are thinking of?

**Comment by alexcrichton** [comment]
@andreytkachenko would `for_each`, `and_then`, or `map` suit your needs?

**Comment by andreytkachenko** [comment]
The problem is rising only when processing streams in async/await manner. Using https://github.com/alexcrichton/futures-await library.

**Comment by andreytkachenko** [comment]
@carllerche Sorry may be I explained not correct:
I would like to have `takeOne` method which behaives just like take, but returns future instead stream (like into_future). Here is the signature:
```rust
fn takeOne(&self) -> impl Future;
```

**Comment by alexcrichton** [comment]
@andreytkachenko ah ok thanks for the clarification! In that case this may be best on the futures-await repository for now which doesn't support borrowed futures that well. In the meantime though I'm going to close this for the `futures` repository because I think this is more specific to futures-await.
