### ISSUE TITLE
Extract io2 out of minihttp and make public more structs

### ISSUE THREAD

**Issue by seppo0010** [alexcrichton/futures-rs#73]
I was trying to implement a non-http server using `future-mio` and the abstractions in `io2.rs` look quite useful for any sort of server, and none of its code is specific to http.

I was wondering if there's a plan to extract those outside of minihttp and make other structs like `ParseStream` publicly available, or if there's a better suggestion for handling these cases.

Thanks

**Comment by alexcrichton** [comment]
Ah yes, indeed! The instances in minihttp are basically just proofs of concept of what we'd like to compile down to eventually. We should have more news on this soon, I'll keep you updated!

(the intent is very much to extract these pieces to reusable components)

**Comment by sbstp** [comment]
I think more utilities are needed, especially on the reading side of things. I looked at the examples provided, `minihttp`, `socks5`, etc, and I get the the feeling that the support for reading is incomplete:

1. `minihttp` implements the `poll` method on the parse stream. This is pretty tedious work as you have to handle `WouldBlock` errors and what not. I don't think this is ideal.
2. `socks5` uses the `read_exact` method a lot, because the protocol permits it. If I was trying to implement an http request parser for instance (without using `poll`), where the length of the message is not known ahead
it would be very hard to do it using the current API.
3. `TcpStream` implements Read, but is set to unblocking mode. This is a bit unintuitive because it shouldn't be used in the context of futures. It will return `Err(WouldBlock)` most of the time. And it shouldn't be busy looped either. Same issue on the `UdpSocket::recv_from`.

It's easy to point out issues, but  it's not always easy to fix them. I'm currently experimenting on ways of solving this, for instance creating a `Stream` of `Vec<u8>` from a `TcpStream`, but it has issues (like allocating a lot). Anyway, thoughts?

**Comment by alexcrichton** [comment]
@sbstp note that using `TcpStream` as a "future" actually works. Whenever you receive `WouldBlock` you can propagate that as `NotReady`, and the future's task will get woken up when data is available again.

Also yes `minihttp` and `socks5` are mostly intended to be examples, not showcases of **the** way to parse and handle data from sockets with futures. Instead the intention is to have more composable abstractions here that can be layered for various protocols, and more info on this will be coming soon!

**Comment by alexcrichton** [comment]
Ok, with the [recent news](https://aturon.github.io/blog/2016/08/26/tokio/) everything is plumbed through quite nicely now and these abstractions are now available as [`Framed`](https://github.com/tokio-rs/tokio-proto/blob/master/src/io/framing.rs#L8) in the tokio-proto crate.
